//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chapter04
{
    using System;
    using System.Collections.Generic;
    
    public partial class vJobCandidateEmployment
    {
        public int JobCandidateID { get; set; }
        public Nullable<System.DateTime> Emp_StartDate { get; set; }
        public Nullable<System.DateTime> Emp_EndDate { get; set; }
        public string Emp_OrgName { get; set; }
        public string Emp_JobTitle { get; set; }
        public string Emp_Responsibility { get; set; }
        public string Emp_FunctionCategory { get; set; }
        public string Emp_IndustryCategory { get; set; }
        public string Emp_Loc_CountryRegion { get; set; }
        public string Emp_Loc_State { get; set; }
        public string Emp_Loc_City { get; set; }
    }
}
