//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chapter04
{
    using System;
    using System.Collections.Generic;
    
    public partial class vJobCandidateEducation
    {
        public int JobCandidateID { get; set; }
        public string Edu_Level { get; set; }
        public Nullable<System.DateTime> Edu_StartDate { get; set; }
        public Nullable<System.DateTime> Edu_EndDate { get; set; }
        public string Edu_Degree { get; set; }
        public string Edu_Major { get; set; }
        public string Edu_Minor { get; set; }
        public string Edu_GPA { get; set; }
        public string Edu_GPAScale { get; set; }
        public string Edu_School { get; set; }
        public string Edu_Loc_CountryRegion { get; set; }
        public string Edu_Loc_State { get; set; }
        public string Edu_Loc_City { get; set; }
    }
}
